apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-demo
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-clinic-demo
  template:
    metadata:
      labels:
        app: pet-clinic-demo
    spec:
      containers:
      - name: pet-clinic-demo
        image: rushi2323/pet-clinic-demo:latest
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-demo-service
  namespace: test
spec:
  selector:
    app: pet-clinic-demo
  ports:
    - protocol: TCP
      port: 80          # External port for the service
      targetPort: 8085  # Port the container is listening on
  type: ClusterIP    # Use LoadBalancer for external access (or ClusterIP for internal)        
